export PATH=$HOME/bin:$PATH

export UDUNITS=/opt/udunits-2.1.24
export PATH=$UDUNITS/bin:$PATH
export LIBRARY_PATH=$UDUNITS/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$UDUNITS/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$UDUNITS/include:$C_INCLUDE_PATH
export UDUNITS_DIR=$UDUNITS

export HDF5=/opt/hdf5-1.8.11
export PATH=$HDF5/bin:$PATH
export LIBRARY_PATH=$HDF5/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$HDF5/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$HDF5/include:$C_INCLUDE_PATH
export HDF5_DIR=$HDF5

export HDF4=/opt/hdf-4.2.9
export PATH=$HDF4/bin:$PATH
export LIBRARY_PATH=$HDF4/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$HDF4/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$HDF4/include:$C_INCLUDE_PATH
export HDF4_DIR=$HDF4

export NETCDF4=/opt/netcdf-4.3.0
export PATH=$NETCDF4/bin:$PATH
export LIBRARY_PATH=$NETCDF4/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$NETCDF4/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$NETCDF4/include:$C_INCLUDE_PATH
export NETCDF4_DIR=$NETCDF4

export LIBEVENT=/opt/libevent-2.0.21-stable
export PATH=$LIBEVENT/bin:$PATH
export LIBRARY_PATH=$LIBEVENT/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$LIBEVENT/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$LIBEVENT/include:$C_INCLUDE_PATH
export LIBEVENT_DIR=$LIBEVENT
